"""Initial migration

Revision ID: 80b65a437638
Revises: 
Create Date: 2025-07-19 15:34:12.368729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b65a437638'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_file_path'), 'files', ['file_path'], unique=True)
    op.create_table('file_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_versions_file_path'), 'file_versions', ['file_path'], unique=False)
    op.create_table('file_diffs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('previous_version_id', sa.String(), nullable=True),
    sa.Column('current_version_id', sa.String(), nullable=False),
    sa.Column('diff_content', sa.Text(), nullable=False),
    sa.Column('diff_type', sa.String(), nullable=False),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.Column('operation_details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_version_id'], ['file_versions.id'], ),
    sa.ForeignKeyConstraint(['previous_version_id'], ['file_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_diffs_file_path'), 'file_diffs', ['file_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_diffs_file_path'), table_name='file_diffs')
    op.drop_table('file_diffs')
    op.drop_index(op.f('ix_file_versions_file_path'), table_name='file_versions')
    op.drop_table('file_versions')
    op.drop_index(op.f('ix_files_file_path'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
